# Generated by Django 5.1.7 on 2026-04-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_memberprofile_onboarding_qr_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("members_onboarded_direct", models.PositiveIntegerField(default=0)),
                ("members_onboarded_network", models.PositiveIntegerField(default=0)),
                ("referral_chain_depth", models.PositiveIntegerField(default=0)),
                ("events_attended", models.PositiveIntegerField(default=0)),
                ("events_organized", models.PositiveIntegerField(default=0)),
                ("announcements_read", models.PositiveIntegerField(default=0)),
                ("reports_submitted", models.PositiveIntegerField(default=0)),
                ("reports_on_time", models.PositiveIntegerField(default=0)),
                ("score_onboarding", models.FloatField(default=0)),
                ("score_attendance", models.FloatField(default=0)),
                ("score_engagement", models.FloatField(default=0)),
                ("score_network_depth", models.FloatField(default=0)),
                ("total_score", models.FloatField(default=0)),
                ("national_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("state_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("lga_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("badges", models.JSONField(blank=True, default=list)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="members.memberprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-total_score"], name="scoring_mem_total_s_7b0dda_idx"
                    ),
                    models.Index(
                        fields=["national_rank"], name="scoring_mem_nationa_d6c6a9_idx"
                    ),
                ],
            },
        ),
    ]
