# Generated by Django 5.1.7 on 2026-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otpverification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="otpverification",
            name="channel",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("EMAIL", "Email")],
                default="SMS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="has_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["phone_number", "is_used", "expires_at"],
                name="accounts_ot_phone_n_2c3a4a_idx",
            ),
        ),
    ]
