# Generated by Django 5.1.7 on 2026-04-02 18:20

import apps.members.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("STATE_DIRECTOR", "State Director"),
                            ("DEPUTY_STATE_DIRECTOR", "Deputy State Director"),
                            ("STATE_COORDINATOR", "State Coordinator"),
                            ("STATE_SECRETARY", "State Secretary"),
                            ("LGA_COORDINATOR", "LGA Coordinator"),
                            ("WARD_COORDINATOR", "Ward Coordinator"),
                            ("UNIT_LEADER", "Unit Leader"),
                        ],
                        max_length=30,
                    ),
                ),
                ("appointed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tenure_ends", models.DateField(blank=True, null=True)),
                (
                    "appointed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.localgovernment",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.ward",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("residential_address", models.TextField(blank=True)),
                ("profile_photo", models.ImageField(blank=True, upload_to="profiles/")),
                ("voter_card_number", models.CharField(blank=True, max_length=50)),
                (
                    "voter_card_image",
                    models.ImageField(blank=True, upload_to="voter_cards/"),
                ),
                (
                    "voter_verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("voter_verified_at", models.DateTimeField(blank=True, null=True)),
                ("apc_membership_number", models.CharField(blank=True, max_length=50)),
                (
                    "membership_category",
                    models.CharField(
                        choices=[
                            ("ORDINARY", "Ordinary"),
                            ("VOLUNTEER", "Volunteer"),
                            ("COORDINATOR", "Coordinator"),
                            ("PATRON", "Patron"),
                        ],
                        default="ORDINARY",
                        max_length=20,
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        default=apps.members.models.generate_referral_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "membership_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("onboarding_step", models.PositiveSmallIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="structure.localgovernment",
                    ),
                ),
                (
                    "polling_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="structure.pollingunit",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="members.memberprofile",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="structure.state",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="structure.ward",
                    ),
                ),
            ],
        ),
    ]
