# Generated by Django 5.2.12 on 2026-04-10 06:46

import apps.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_memberprofile_onboarding_qr_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="onboarding_qr_token",
            field=models.CharField(
                default=apps.members.models.generate_qr_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
