# Generated by Django 5.1.7 on 2026-04-02 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrassrootsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_period", models.CharField(max_length=20)),
                (
                    "report_level",
                    models.CharField(
                        choices=[("WARD", "Ward"), ("LGA", "LGA"), ("STATE", "State")],
                        max_length=10,
                    ),
                ),
                ("summary_of_activities", models.TextField()),
                ("membership_new", models.PositiveIntegerField(default=0)),
                ("membership_total", models.PositiveIntegerField(default=0)),
                ("events_held", models.PositiveIntegerField(default=0)),
                ("challenges", models.TextField(blank=True)),
                ("plans_next_period", models.TextField(blank=True)),
                ("support_needed", models.TextField(blank=True)),
                ("media_highlights", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("REVIEWED", "Reviewed"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.localgovernment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="structure.state",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
