# Generated by Django 5.1.7 on 2026-04-14 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RETAIL", "Retail/Shop"),
                            ("FOOD", "Food & Restaurant"),
                            ("FASHION", "Fashion & Clothing"),
                            ("TECH", "Technology & IT"),
                            ("HEALTH", "Health & Wellness"),
                            ("BEAUTY", "Beauty & Grooming"),
                            ("EDUCATION", "Education & Training"),
                            ("LOGISTICS", "Logistics & Transport"),
                            ("AGRICULTURE", "Agriculture & Farming"),
                            ("MEDIA", "Media & Entertainment"),
                            ("CONSTRUCTION", "Construction & Real Estate"),
                            ("FINANCE", "Finance & Insurance"),
                            ("LEGAL", "Legal Services"),
                            ("AUTO", "Auto & Mechanic"),
                            ("HOME_SERVICES", "Home Services"),
                            ("EVENT_SERVICES", "Event Services"),
                            ("CONSULTING", "Consulting"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(max_length=2000)),
                ("address", models.TextField(blank=True, max_length=500)),
                ("operates_nationwide", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="opportunities/businesses/logos/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.localgovernment",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="opportunities/businesses/gallery/"),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="opportunities.businesslisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=5000)),
                ("requirements", models.TextField(blank=True, max_length=3000)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("FREELANCE", "Freelance"),
                            ("INTERNSHIP", "Internship"),
                            ("VOLUNTEER", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("ONSITE", "On-site"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="ONSITE",
                        max_length=10,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Level"),
                            ("MID", "Mid Level"),
                            ("SENIOR", "Senior Level"),
                            ("LEAD", "Lead/Manager"),
                            ("ANY", "Any Level"),
                        ],
                        default="ANY",
                        max_length=10,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="NGN", max_length=5)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("hide_salary", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PAUSED", "Paused"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("application_email", models.EmailField(blank=True, max_length=254)),
                ("application_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.state",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_listings",
                        to="opportunities.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("education", models.JSONField(blank=True, default=list)),
                ("work_experience", models.JSONField(blank=True, default=list)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True, null=True, upload_to="opportunities/cvs/"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="professionals",
                        to="opportunities.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TalentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHOTOGRAPHY", "Photography"),
                            ("VIDEOGRAPHY", "Videography"),
                            ("GRAPHIC_DESIGN", "Graphic Design"),
                            ("WEB_DEVELOPMENT", "Web Development"),
                            ("MUSIC", "Music"),
                            ("DJ", "DJ"),
                            ("MC", "MC/Host"),
                            ("FASHION", "Fashion/Tailoring"),
                            ("BARBING", "Barbing/Hairstyling"),
                            ("MAKEUP", "Makeup"),
                            ("CATERING", "Catering/Food"),
                            ("MECHANIC", "Mechanic/Auto"),
                            ("ELECTRICAL", "Electrical"),
                            ("PLUMBING", "Plumbing"),
                            ("CARPENTRY", "Carpentry"),
                            ("LEGAL", "Legal Services"),
                            ("ACCOUNTING", "Accounting/Tax"),
                            ("HEALTH", "Health/Medical"),
                            ("TEACHING", "Teaching/Tutoring"),
                            ("FITNESS", "Fitness/Sports"),
                            ("WRITING", "Writing/Content"),
                            ("MARKETING", "Marketing/PR"),
                            ("EVENT_PLANNING", "Event Planning"),
                            ("DRIVING", "Driving/Logistics"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("bio", models.TextField(max_length=1000)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("available_nationwide", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("show_whatsapp", models.BooleanField(default=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.localgovernment",
                    ),
                ),
                (
                    "service_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.state",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TalentPortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("image", models.ImageField(upload_to="opportunities/portfolio/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "talent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="opportunities.talentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, max_length=3000)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="opportunities/job_applications/",
                    ),
                ),
                ("use_profile_cv", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("REVIEWED", "Reviewed"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEW", "Interview"),
                            ("OFFERED", "Offered"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=15,
                    ),
                ),
                ("recruiter_notes", models.TextField(blank=True, max_length=1000)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="opportunities.joblisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="opportunities.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("user", "job")},
            },
        ),
    ]
